[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
extra_scripts = pre:build_timestamp.py

; Dependencies
lib_deps =
    mikalhart/TinyGPSPlus @ ^1.0.3

; Build Options
build_flags =
    -D USB_SERIAL ; Enable USB Serial for debugging
    -D TEENSY_OPT_FASTER ; Optimize for speed
    -D __FPU_PRESENT=1

lib_ldf_mode = deep+

; Monitor Options
monitor_speed = 115200

[env:esp32]
platform = espressif32
board = wt32-eth01
framework = arduino
upload_port = COM12
monitor_speed = 115200
extra_scripts = pre:build_timestamp.py
; Point to the ESP32 firmware source
build_src_filter = +<../esp32_firmware/Spirit/> -<src/>
